name = "VectorUtils"
uuid = "ce5ad29b-8b1a-4d19-a814-cc15ce7eccd1"
version = "1.0.0"
authors = ["Miraj Samarakkody <miraj.samarakkody@gmail.com>"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "1.16.0"
LinearAlgebra = "1.12.0"
Pkg = "1.12.0"
QuadGK = "2.11.2"
SymPy = "2.3.3"
Test = "1.11.0"
julia = "1.12"
